### ISSUE TITLE
License conflict for SHA1

### ISSUE THREAD

**Issue by riadhelloumi** [cjhdev/wic#1]
Hello,

The SHA1 computation in wic.c seems to be originating from this project:

https://github.com/legitbs/quals-2013/blob/master/bitterswallow/sha1.c

Since the license of originating code is "Creative Commons Attribution-NonCommercial 3.0 License", there is a license conflict with your license (MIT).

Best regards,
Riadh

**Comment by cjhdev** [comment]
The code in question originates from MBED TLS (formerly PolarSSL, formerly XySSL). License banners are embedded in the source as required, I also make it clear in the readme that this project integrates third party source.

The top level LICENSE text applies only to my original code. I will update the text in LICENSE to make this more clear.

The repository you have linked has a similar problem I think.
